packages:
  - 'playgrounds/*'
  - 'packages/*'

catalogs:
  bundler:
    rolldown: 1.0.0-beta.39
    rolldown-plugin-dts: ^0.16.11
  dev:
    typescript: ^5.9.2
  test:
    vitest: ^3.2.4
  tool:
    '@antfu/eslint-config': ^5.4.1
    bumpp: ^10.2.3
    eslint: ^9.36.0
    lint-staged: ^16.2.3
  types:
    '@types/node': ^24.5.2

minimumReleaseAge: 1440

onlyBuiltDependencies:
  - esbuild
