catalogs:
  bundler:
    rolldown: 1.0.0-beta.39
    rolldown-plugin-dts: ^0.16.11
    rollup-plugin-copy: ^3.5.0
  dev:
    typescript: ^5.9.2
  prod:
    '@inquirer/prompts': ^7.8.6
    chalk: ^5.6.2
    commander: ^14.0.1
    fs-extra: ^11.3.2
    node-lts-versions: ^1.7.3
    tinyexec: ^1.0.1
  test:
    vitest: ^3.2.4
  tool:
    '@antfu/eslint-config': ^5.4.1
    bumpp: ^10.2.3
    eslint: ^9.36.0
    husky: ^9.1.7
    lint-staged: ^16.2.3
    semantic-release: ^24.2.9
  types:
    '@types/fs-extra': ^11.0.4
    '@types/node': ^24.5.2

minimumReleaseAge: 1440

onlyBuiltDependencies:
  - esbuild
