name: Test

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: oven-sh/setup-bun@v2
      - uses: actions/setup-node@v5
        with:
          node-version-file: .node-version
      - run: bun install
      - run: bun run lint
      - run: bun run typecheck

  # test:
  #   runs-on: ${{ matrix.os }}

  #   strategy:
  #     matrix:
  #       node: [lts/*]
  #       os: [ubuntu-latest, windows-latest, macos-latest]
  #     fail-fast: false

  #   steps:
  #     - uses: actions/checkout@v5
  #     - uses: oven-sh/setup-bun@v2
  #     - uses: actions/setup-node@v5
  #       with:
  #         node-version: ${{ matrix.node }}
  #         registry-url: https://registry.npmjs.org/
  #     - run: bun install
  #     - run: bun run build
  #     - run: bun run test
