name: Test

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v5
        with:
          node-version-file: .node-version
          registry-url: https://registry.npmjs.org/
      - run: pnpm install
      - run: pnpm lint
      - run: pnpm typecheck

  # test:
  #   runs-on: ${{ matrix.os }}

  #   strategy:
  #     matrix:
  #       node: [lts/*]
  #       os: [ubuntu-latest, windows-latest, macos-latest]
  #     fail-fast: false

  #   steps:
  #     - uses: actions/checkout@v5
  #     - uses: pnpm/action-setup@v4
  #     - uses: actions/setup-node@v5
  #       with:
  #         node-version: ${{ matrix.node }}
  #         registry-url: https://registry.npmjs.org/
  #     - run: pnpm install
  #     - run: pnpm build
  #     - run: pnpm test
